name: 'redmine-plugin-test-action'
description: 'This action is to test for Redmine plugin.'
author: 'Tatsuya Saito'
inputs:
  plugin_name:
    description: 'The name of the plguin to test.'
    required: true
  redmine_version:
    description: 'The version of Redmine to test.'
    required: true
  ruby_version:
    description: 'The version of ruby to test.'
    required: true
  database:
    description: 'The database of Redmine to test.'
runs:
  using: 'node12'
  main: 'lib/redmine-plugin-test.js'
branding:
  icon: 'check-square'
  color: 'green'
